baseURL = "https://blog.nathandines.com/"
languageCode = "en"
title = "nathandines_blog"
theme = "tale"
googleAnalytics = "UA-136326060-1"
pygmentsCodefences = true
pygmentsStyle = 'emacs'

[Author]
    name = "Nathan Dines"

[Params]
    author = "Nathan Dines"
    windowTitle = "Nathan Dines Blog"
    description = "A place where I write about things I've been doing or am interested in. Follow along if you like."
