[build]
    command = "hugo --gc --minify"
    publish = "public"

[build.environment]
    HUGO_VERSION = '0.54.0'

[context.branch-deploy]
    command = 'hugo --gc --minify --buildFuture -b "$DEPLOY_PRIME_URL"'

[[redirects]]
    from = "https://blog-nathandines-com.netlify.com/*"
    to = "https://blog.nathandines.com/:splat"
    status = 301
    force = true
